apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: prod
spec:
  metrics:
    enable: true
  statefulSet:
    pod:
      tailscaleContainer:
        env:
        - name: TS_LOCAL_ADDR_PORT
          value: "0.0.0.0:10000"
